server:
  port: 4503
  servlet:
    contextPath: /travian-task-queue
spring:
  application:
    name: travian-task-list
  datasource:
    url: jdbc:mysql://localhost:3306/travian_task?autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: travianadmin
    password: Antaheen@4813
    tomcat:
      max-active: 30
      max-idle: 15
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jmx:
    default-domain: travian-task-list
logging:
  level:
    root: WARN
    com:
      travian: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate: WARN
      apache:
        commons:
          dbcp2: ERROR
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%X{X-B3-TraceId:-}] [%thread] %logger{15} - %msg%n'
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%X{X-B3-TraceId:-}] [%thread] %logger{15} - %msg%n'
  file: /usr/local/log/travian-task.log