spring:
  application:
    name: travian-task-list
logging:
  level:
    root: WARN
    com:
      travian: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate: WARN
      apache:
        commons:
          dbcp2: ERROR
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  file: /usr/local/log/travian-task.log